### ISSUE TITLE
Pusher endpoint for syncing

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#118]
Create an endpoint that allows for sending pusher updates to clients when a user creates/ edits / deletes a task

- [x] integrate pusher service call in task services
- [x] test
- [x] Client needs new task status for that

**Comment by 5v3nn** [comment]
- [ ] Client needs new task status for that: `IN_SESSION_DONE` so that the client can issue a put request which tiggers the pusher update

**Comment by 5v3nn** [comment]
pr: #127 #128

**Comment by 5v3nn** [comment]
merged
