### ISSUE TITLE
Login API endpoint(s) according to rest specification

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#16]

**Comment by Monti934** [comment]
Impediment: need UserService 
Impediment: what should be returned

**Comment by 5v3nn** [comment]
login service already done in #82 
i did now the login endpoint and tests

**Comment by 5v3nn** [comment]
> Impediment: need UserService Impediment: what should be returned

resolved

**Comment by 5v3nn** [comment]
simultaneously implemented with #15
