### ISSUE TITLE
AI generated team description

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#193]
As a user,
I want to click a "generate Team description" button on team creation,
to get an AI generated team description based on my team name.

---
Frontend:
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#114

Backend:
- [x] #195
- [x] #196
- [x] #197
- [x] #198
- [x] #199

**Comment by 5v3nn** [comment]
done and tested
