### ISSUE TITLE
Account Creation API endpoint

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#20]

**Comment by 5v3nn** [comment]
pr: https://github.com/sopra-fs24-group07/sopra-fs24-group-07-server/pull/90

**Comment by 5v3nn** [comment]
merged

**Comment by Monti934** [comment]
Problem: wo dont get the token from the Register endpoint /api/v1/users, only username and name

**Comment by 5v3nn** [comment]
works as designed (see rest specification)
