### ISSUE TITLE
Team Dashboard

### ISSUE THREAD

**Issue by 5v3nn** [sopra-fs24-group07/sopra-fs24-group-07-server#28]
As a user
I want to access the team dashboard
to see that tasks, my team members, also communicate with them, and to start the session.

Acceptance Criterias
- [x] Dashboard with widgets and content (bot no functionality yet)
- [x] All tasks and team member should be visible
- [x] The user can go further from here (i.e., start session, create tasks, manage team)

---

Frontend
- [x] https://github.com/sopra-fs24-group07/sopra-fs24-group-07-client/issues/6 
- [x] sopra-fs24-group07/sopra-fs24-group-07-client#35

Backend
- [x] sopra-fs24-group07/sopra-fs24-group-07-server#32 (edit tasks status and get all tasks)
- [x] #130

**Comment by B1s9l** [comment]
@5v3nn Can the "help wanted" label be removed or does this task need further attention?

**Comment by 5v3nn** [comment]
> @5v3nn Can the "help wanted" label be removed or does this task need further attention?

was done, is removed now.

**Comment by 5v3nn** [comment]
done
