### ISSUE TITLE
Share session state and content to users

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#69]
(such as goal and progress) 
- [x] Create an endpoint that returns the session state and content from the session service call

**Comment by 5v3nn** [comment]
pusher setup on both start and end session
see pr: #121

**Comment by 5v3nn** [comment]
Was thanks to @B1s9l; i just got the relevant code from his branch

**Comment by 5v3nn** [comment]
merged
