### ISSUE TITLE
User service session content

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#70]
- [x] Create a service that returns information
- [x] Attach the time goal to the return
- [ ] Attach the active members to the return
- [ ] Attach the session progress to the return
- [ ] Attach the task info to the return

**Comment by 5v3nn** [comment]
is done in client
- Attach the active members to the return
- Attach the session progress to the return

will not be implemented (different way found)
- Attach the task info to the return
