### ISSUE TITLE
User service to start session

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#71]
- [x] Create a service that handles the start of a session
- [x] On call create a new session and input the time goal
- [x] Think about how to handle an ongoing session -> how do we send the current progress to the frontend? -> frontend checks if endDateTime is not set

**Comment by 5v3nn** [comment]
pr: https://github.com/sopra-fs24-group07/sopra-fs24-group-07-server/pull/119

**Comment by 5v3nn** [comment]
merged
