### ISSUE TITLE
API endpoint for user data

### ISSUE THREAD

**Issue by B1s9l** [sopra-fs24-group07/sopra-fs24-group-07-server#78]
- [x] Create an API endpoint that returns a user
- [x] Call the corresponding service to get the user data from the user in the database
- [x] Return the user data
- [x] tests
- [x] docu

**Comment by 5v3nn** [comment]
could reuse auth service, because we designed that to return the authorized user.

**Comment by 5v3nn** [comment]
see pr: #124

**Comment by 5v3nn** [comment]
merged
